"""
Catan view and other view constants subtracting dev card view
All magic numbers, colors, paths, costs, and configuration.
Every other file imports from here.
"""

# CatanView layout / HUD
CATAN_BTN_W = 120
CATAN_BTN_H = 38
CATAN_BTN_GAP = 8
CATAN_BTN_PAD = 14
CATAN_END_BTN_W = 130

CATAN_BUILD_SUBMENU_W = CATAN_BTN_W
CATAN_BUILD_SUBMENU_H = 120
CATAN_BUILD_SUBMENU_Y_OFFSET = 4
CATAN_BUILD_SUBMENU_BTN_INSET = 8
CATAN_BUILD_SUBMENU_BTN_H = 28
CATAN_BUILD_SUBMENU_ROW_STEP = 36

CATAN_CONFIRM_POPUP_W = 160
CATAN_CONFIRM_POPUP_H = 70
CATAN_CONFIRM_BTN_W = 66
CATAN_CONFIRM_BTN_H = 30
CATAN_CONFIRM_Y_OFFSET = 18
CATAN_CONFIRM_TITLE_Y_PAD = 14
CATAN_CONFIRM_BTN_CENTER_Y = 23
CATAN_CONFIRM_BTN_INSET = 8

CATAN_DICE_BOX_MARGIN = 10
CATAN_DIE_SIZE = 40
CATAN_DIE_GAP = 12
CATAN_DICE_Y_OFFSET = 20
CATAN_DICE_LABEL_TOP_PAD = 16
CATAN_DICE_TOTAL_Y = 7

CATAN_PLAYER_PANEL_MARGIN = 8
CATAN_PLAYER_MARKER_RADIUS = 7
CATAN_PLAYER_NAME_Y = 18
CATAN_PLAYER_ROW_H = 24
CATAN_RESOURCE_TEXT_X_OFFSET = 35
CATAN_RESOURCE_ROW_GAP = 8
CATAN_RESOURCE_ICON_X_OFFSET = 14
CATAN_RESOURCE_ICON_Y_OFFSET = 8
CATAN_RESOURCE_ICON_ROW_GAP = 8
CATAN_DEV_CARD_COUNT_Y_OFFSET = 10
CATAN_DEV_CARD_COUNT_COLOR = (180, 120, 255)

CATAN_TEXT_SIZE_BTN = 12
CATAN_TEXT_SIZE_CARD_BTN = 11
CATAN_TEXT_SIZE_DICE_LABEL = 11
CATAN_TEXT_SIZE_DICE_HINT = 8
CATAN_TEXT_SIZE_DICE_NUM = 18
CATAN_TEXT_SIZE_TOTAL = 9
CATAN_TEXT_SIZE_SUBMENU = 9
CATAN_TEXT_SIZE_POPUP_TITLE = 10
CATAN_TEXT_SIZE_POPUP_BTN = 9
CATAN_TEXT_SIZE_PLAYER_NAME = 12
CATAN_TEXT_SIZE_PLAYER_VP = 10
CATAN_TEXT_SIZE_RESOURCE = 10
CATAN_TEXT_SIZE_FREE_ROADS = 8

CATAN_LABEL_TRADE = "Trade"
CATAN_LABEL_BUILD = "Build"
CATAN_LABEL_DEV_CARDS = "Dev Cards"
CATAN_LABEL_END_TURN = "End Turn"
CATAN_LABEL_DICE_ROLL = "Dice Roll"
CATAN_LABEL_DICE_HINT = "Auto-rolls on turn start"
CATAN_LABEL_CANCEL = "Cancel"
CATAN_LABEL_CITY = "City"
CATAN_LABEL_SETTLEMENT = "Settlement"
CATAN_LABEL_ROAD = "Road"

CATAN_COLOR_DROP_SHADOW = (0, 0, 0, 100)
CATAN_COLOR_BTN_OUTLINE = (255, 255, 255, 60)
CATAN_COLOR_DISABLED = (70, 70, 70)
CATAN_COLOR_CITY_BTN = (255, 102, 0)
CATAN_COLOR_SETTLEMENT_BTN = (39, 174, 96)
CATAN_COLOR_ROAD_BTN = (52, 152, 219)
CATAN_COLOR_POPUP_BG = (20, 20, 40, 220)
CATAN_COLOR_POPUP_CANCEL = (180, 50, 50)
CATAN_COLOR_POPUP_NO_RES = (80, 80, 80)
CATAN_COLOR_FREE_ROADS = (100, 255, 100)
CATAN_COLOR_DIE_BG = (248, 248, 248)
CATAN_COLOR_DIE_FALLBACK = (60, 60, 90)
CATAN_COLOR_SHAKE_OUTLINE = (255, 215, 0)
CATAN_COLOR_GHOST_FILL = (255, 255, 255, 60)
CATAN_COLOR_GHOST_OUTLINE = (255, 255, 255, 120)
CATAN_COLOR_PORT_HOVER_OUTER = (255, 215, 0, 55)
CATAN_COLOR_PORT_HOVER_INNER = (255, 215, 0, 120)

CATAN_HIGHLIGHT_RADIUS_HOVER = 12
CATAN_HIGHLIGHT_RADIUS_OUTLINE = 14
CATAN_HIGHLIGHT_RADIUS_IDLE = 8
CATAN_EDGE_HIGHLIGHT_WIDTH = 6
CATAN_EDGE_IDLE_WIDTH = 3
CATAN_EDGE_HOVER_DOT_RADIUS = 7
CATAN_PORT_HOVER_OUTER_RADIUS = 16
CATAN_PORT_HOVER_INNER_RADIUS = 11
CATAN_PORT_HOVER_OUTLINE_RADIUS = 12

CATAN_BOARD_TOP_CULL_Y = 10
CATAN_HUD_LEFT_BLOCK_PAD = 5
CATAN_DICE_RIGHT_BLOCK_PAD = 15

CATAN_SETTLEMENT_DRAW_SIZE = 14
CATAN_CITY_DRAW_SIZE = 18
CATAN_ROBBER_SCALE_MULT = 1.1